BASE.name = "Base Plant"
BASE.uniqueID = "base_plant"
BASE.weight = 1
BASE.category = "Plants / Drugs"
BASE.cantdrop = false
BASE.rotate = 90
--BASE.CanTransfer = true
BASE.sellFactor = 1
BASE.plant = "freshOlive"
BASE.plantmdl = "models/props/cs_office/plant01_p1.mdl"
BASE.time = 60