--nut.lang.Add("weapons_melee", "Melee")
nut.lang.Add("weapons_melee", "근접 무기")
--nut.lang.Add("weapons_ranged", "Firearms")
nut.lang.Add("weapons_ranged", "총화기")
--nut.lang.Add("ammo_cat", "Consumeable - Ammo")
nut.lang.Add("ammo_cat", "탄약")

--nut.lang.Get("weapons_ranged")
-- Personal Item List.

--nut.lang.Add("desc_wep_9mm", "A 9mm Pistol. Uses Pistol Ammo, Has 12 bullets capacity, does Mid-high damage.")
nut.lang.Add("desc_wep_9mm", "9mm 자동권총. 권총탄을 사용하며, 12발을 장전할 수 있다. 중상 데미지.")
--nut.lang.Add("desc_wep_357", "A .357 Magnum. Uses 357 Ammo, Has 6 bullets capacity, does High damage.")
nut.lang.Add("desc_wep_357", ".357 매그넘 리볼버. 357 탄을 사용하며, 6발을 장전할 수 있다. 높은 데미지.")
--nut.lang.Add("desc_wep_smg1", "A Sub-Machine Gun. Uses SMG Ammo, Has 30 bullets capacity, does Mid-low damage. Has optic on the gun.")
nut.lang.Add("desc_wep_smg1", "MP7 모델형 머신건. SMG 탄을 사용하고, 30발을 장전할 수 있다. 중하 데미지. 총에 광학조준도구가 달려있다.")
--nut.lang.Add("desc_wep_ar2", "A Combine Issue Carbine Rifle. Uses AR2 Cartridge, Has 30 bullets capacity, does Mid-high damage. Ball-option is not included.")
nut.lang.Add("desc_wep_ar2", "콤바인제 카빈 라이플. AR2 카트리지를 사용하며, 30발을 장전할 수 있다, 중상 데미지. 압축탄 옵션은 제거되있다.")
--nut.lang.Add("desc_wep_shotty", "A SPAS Model Shotgun. Uses Buckshot, Has 8 bullets capacity, does High damage in Close Quarter.")
nut.lang.Add("desc_wep_shotty", "SPAS 모델의 산탄총. 산탄을 사용하며, 8발을 넣을 수 있다, 근접 교전시 높은 데미지를 준다.")
--nut.lang.Add("desc_wep_mp5k", "A Sub-Machine Gun. Uses Pistol Ammo, Has 25 bullets capacity, does Mid-low damage. Does not have stock. Increased Mobility.")
nut.lang.Add("desc_wep_mp5k", "MP5K 모델형 머신건. 권총탄을 사용하고, 25발을 장전할 수 있다. 중하의 데미지를 제공하며 개머리판의 제거로 높은 기동성을 추구할 수 있다.")
--nut.lang.Add("desc_wep_sniper", "A Really Huge Sniper Rifle. Uses Compact Pulse Ammo, Has one bullets capacity, does Extremely High damage. Laser sight is included.")
nut.lang.Add("desc_wep_sniper", "대물저격총. 컴팩트 펄스 카트리지를 사용하며, 한 발만 장전이 가능. 극상의 데미지를 제공, 레이저 사이트가 기본으로 달려있다.")